#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://chipchirp.digital" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
permalink: ChipChirp #/:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-mermaid

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  style: compressed

mastodon: "https://ioc.exchange/@chipchirp"
