#-------------------------------
# Site Settings
title: " Chip☄<br>Chirp"
#title: " ☾hip<br>☾hirp"
#title: "⛆Chip⚵⛆<br>⛆Chirp⛆"
#title: "⛆Chip⚗<br>⛆Chirp"
#title: "Chip⚟<br>Chirp"
logo: # You can add own logo. For example '/images/logo.png'.
description: 𓏞 Audio, oddware, and more


#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'About Me'
      url: '/about/'
      #- title: 'Contact Me'
      #url: '/contact/'
    #- title: 'Reading'
    #  url: '/reading_list/'


#-------------------------------
# Author Settings
author:
  name: Amber Harrington
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: Amber Harrington<br>𓏞
  description:  Making noises & stuff.
  image: '/images/06.jpg'


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your email for contact form
  description: Norlin comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
social:
- {icon: "fa-brands fa-bluesky", name: "Bluesky", link: "https://bsky.app/profile/sesheta.bsky.social"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://ioc.exchange/@chipchirp"}
#- {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
#- {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://dribbble.com"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/en_somnia_music"}
#- {icon: "fa-brands fa-pinterest", name: "Pinterest", link: "https://pinterest.com"}
- {icon: "fa-brands fa-youtube", name: "Youtube", link: "https://youtube.com/@chipchirp_en_somnia"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/KO0I"}
#- {icon: "fa-brands fa-vimeo-v", name: "Vimeo", link: "https://vimeo.com/"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social/"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
mailchimp-button-text: Join
