I"∏j<h1 id="3d-printing-practical-items-overview-of-a-process">3D Printing Practical Items, Overview of A Process</h1>

<p>I‚Äôve been using OpenSCAD to create things to 3D-print for years now, and it
can be a simple and fulfilling process to build up something useful from simple
geometric primitives.</p>

<p><a href="www.openscad.org">OpenSCAD</a> is a ‚Äúprogrammer‚Äôs CAD‚Äù where the models are written up in text, a bit like a program, and
rendered as needed. There are a variety of geometric primitives available to
the user that can be built up into more complicated modules. It allows for natural
parameterization and I strongly prefer the simplicity of it to GUI-driven tools like AutoCAD, largely because by making the right choices</p>

<p>This post will cover:</p>

<ul>
  <li>Gathering requirements for an object</li>
  <li>Making a sketch</li>
  <li>Rough Arrangement in Space</li>
  <li>Identifying critical dimensions</li>
  <li>Breaking down the model into smaller and smaller parts</li>
  <li>Writing up the OpenSCAD model</li>
  <li>Basic Testing in OpenSCAD</li>
  <li>Printing and testing in the Real World</li>
</ul>

<h2 id="gathering-requirements">Gathering Requirements</h2>

<p>So there‚Äôs a bunch of things in the shower area that could be hung up. I‚Äôm
talking razors and a brush. There are four razors and two brushes, both a bit
different.</p>

<p>I want to use command strips to affix a holder or holders to a part of the shower, and then
have it so that razors can be placed onto C-shaped grabbers instead of being
scattered about the shower taking up precious space. I want to size the inner diameter to roughly
correspond to each razor. It would be ideal to have it be snug, but not
requiring force to bend the plastic back and forth.</p>

<p>If I decided to have all of them on a common backing I would have to consider
grouping the razors together in some way. However, since each razor and brush
is a little different, it will be easier to print a holder per item.</p>

<p>In my humble opinion, when creating practical objects that need to fit nicely,
it‚Äôs nicer to work towards a simple, parameterized core that can be adapted for as
many of the cases as possible. This is partly because I‚Äôm lazy and mostly
because wasting filament is bad. If I needed to have a common backing I‚Äôd
probably go through and make some prototype for the fitted sections so that
the material needed for a common backing would not be wasted in multiple
attempts.</p>

<h2 id="making-a-sketch">Making a Sketch</h2>

<p>Try drawing a rough image of the constituent elements and get thinking about
how things will come together. Do not worry about how you would code it up or get clever at this point, just draw a few things and see what comes up.</p>

<p>I first drew a common backing, and spaced the holders evenly. If there was a common backing, it would be importand that the razor holders are far enough apart so that
the razors don‚Äôt bump into one another. There are other thoughts that come up
when sketching, such as that the holders can‚Äôt be too tall since
most of the razors have a varied shape along the length, and the inner diameter and possibly the
shape in the middle has to be reasonable enough to meet the snugness
requirement.</p>

<p>The process of drawing is helpful to quickly remove the vaguaries of a
purely mental picture, and it allows you to start asking focused questions about the design in question.</p>

<p>It is also generally cheaper and faster to tinker on paper than it is with a long string of failed physical prototypes.</p>

<h2 id="rough-arrangement-in-space">Rough Arrangement in Space</h2>

<p>If possible, arranging the objects or other prototype items is able to help
provide additional insights. For one, gnolling the items in question revealed that
the razors each have a bit of a height offset. If the common backing was
preferred, it might be nice to try to align the business ends of the razors to
be at the same height, this would mean the clamps would be higer and lower
along the common backing, or noting that seperate holders would have to be
placed at various heights.</p>

<p><img src="/assets/openscad_gnoll.png" alt="Razors and Brushes" /></p>

<p>The combination of a sketch and manipulating the objects is valuable to test
assumptions and work out important details.</p>

<h2 id="identifying-critical-dimensions">Identifying critical dimensions</h2>

<p>After creating a sketch, I was able to identify some dimensions that were
important and that I would have to measure out.</p>

<p>So the dimensions I noted as being important are:</p>

<ul>
  <li>The specific diameter of the razors</li>
  <li>The minimum gap between any two razors (be equal to the span of the
longest razor)</li>
  <li>The ‚Äúheight‚Äù of the holders</li>
  <li>The ‚Äúheight‚Äù of the brush-holder</li>
  <li>The dimensions of command strips</li>
</ul>

<p>There are other dimensions to think about, such as the per-user gap considered
earlier.</p>

<p>There‚Äôs also the possible dimesnions of a
chamfer on the inner part of the holders, which could have an angle that I
would like to match up with the razors of my roommate that have a ‚ÄúV‚Äù shape
that connects to the business end.</p>

<p>There‚Äôs also the thickness of the holder parts themselves, but when it comes
to these various elements, there‚Äôs a frugality to limiting the material used
to accomplish the task to be balanced against a need for ruggedness for long-term use. Each holder has to take a static force of the weight of the razor, which is probably trivial. But if the user is trying to force a large razor into a smaller razor slot, how beefy should the C-clamp connect to the backing that is to go up against the wall?</p>

<p>For a design that is likely to have to deal with a heavy static loads (i.e a sledgehammer) or has to deal with dynamic loading, the object might need to have a shape that allows more a more complete connection. Strength is proportional to the areas that intersect.</p>

<p>If in the process of sussing out these critical dimensions, feel free to
redraw the sketch with any new details. It is generally quicker to sketch it
than to put things together in OpenSCAD, and it helps to make any mistakes
very obvious if there‚Äôs a rough image in mind when going on to create the model.</p>

<h2 id="breaking-up-the-model-into-smaller-parts">Breaking up the model into smaller parts</h2>

<p>I determined I could break down the design into three different parts,
possibly four.</p>

<ul>
  <li>The backing</li>
  <li>The C-shaped holders for a razor</li>
  <li>A spoon-shape for the round scrubbing brush</li>
  <li>Possibly: a unique holder for the shaving cream brush</li>
</ul>

<p>The holders for the four razors will all be derived from the same module. The holder for the brush
might be shorter in height and so there‚Äôs a possibility I‚Äôll do something
different for that, but it will be similar to the other parts, so perhaps I
can get away with using the razor module with some different parameters.</p>

<p>We could try to have all the clamps go onto a single backing, but for the sake
of simplicity, I‚Äôll be creating independent holders with their own backings
rather than all the holders on one backing.</p>

<h2 id="writing-up-the-openscad-model">Writing up the OpenSCAD model</h2>

<p>Now that we know what the final product will look like, have an idea of what
success looks like, and we know some important values, I am ready to code up
the smaller parts.</p>

<h3 id="backing-and-hull">Backing and hull()</h3>

<p>Let‚Äôs start with the backing. It will be rectangular, but I want the edge to
not be sharp. To make the bevel, I can use the hull() function. A simple
way to describe what the hull() function does is to imagine that it
takes in whatever objects and covers them all in shrink-wrap. The result is a
single object whose outer boundaries are defined by the objects involved.</p>

<p>In the below snippet, points are defined that are the distance equal to the
width of the command strip sticky tape. opencad can iterate through a list of
points with a for-loop.</p>

<p>At those points, I have half-spheres
centered with some radius and use the hull() function to tie it all together.</p>

<figure class="highlight"><pre><code class="language-c" data-lang="c"><table class="rouge-table"><tbody><tr><td class="gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
</pre></td><td class="code"><pre><span class="n">cmdstrip_x</span> <span class="o">=</span> <span class="mi">69</span><span class="p">.</span><span class="mi">31</span><span class="p">;</span>
<span class="n">cmdstrip_y</span> <span class="o">=</span> <span class="mi">19</span><span class="p">;</span>

<span class="n">corner_points</span> <span class="o">=</span> <span class="p">[</span> <span class="p">[</span><span class="o">-</span><span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span> <span class="o">-</span><span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span>
                <span class="p">[</span>   <span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span> <span class="o">-</span><span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span>
                <span class="p">[</span>  <span class="o">-</span><span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span>
                <span class="p">[</span>   <span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="p">(</span><span class="n">cmdstrip_y</span><span class="p">)</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span>  <span class="mi">0</span><span class="p">]</span> <span class="p">];</span>

<span class="n">global_fn</span> <span class="o">=</span> <span class="mi">50</span><span class="p">;</span>

<span class="n">module</span> <span class="nf">half_sphere</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">2</span><span class="p">)</span> <span class="c1">// default radius of 2mm</span>
<span class="p">{</span>
  <span class="n">diam</span> <span class="o">=</span> <span class="mi">2</span><span class="o">*</span><span class="n">radius</span><span class="p">;</span>
  <span class="n">difference</span><span class="p">()</span>
  <span class="p">{</span>
    <span class="n">sphere</span><span class="p">(</span><span class="n">r</span><span class="o">=</span><span class="n">radius</span><span class="p">,</span> <span class="err">$</span><span class="n">fn</span> <span class="o">=</span> <span class="n">global_fn</span><span class="p">);</span>
    <span class="n">translate</span><span class="p">([</span><span class="o">-</span><span class="n">radius</span><span class="p">,</span> <span class="o">-</span><span class="n">radius</span><span class="p">,</span> <span class="o">-</span><span class="n">diam</span><span class="p">])</span>
      <span class="n">cube</span><span class="p">([</span><span class="n">diam</span><span class="p">,</span> <span class="n">diam</span><span class="p">,</span> <span class="n">diam</span><span class="p">]);</span>
  <span class="p">}</span>
<span class="p">}</span>

<span class="n">module</span> <span class="nf">backing</span><span class="p">(</span><span class="n">points</span><span class="p">)</span>
<span class="p">{</span>
  <span class="n">hull</span><span class="p">()</span>
  <span class="p">{</span>
     <span class="k">for</span><span class="p">(</span><span class="n">p</span> <span class="o">=</span> <span class="n">points</span><span class="p">)</span>
      <span class="n">translate</span><span class="p">(</span><span class="n">p</span><span class="p">)</span> <span class="n">half_sphere</span><span class="p">(</span><span class="n">radius</span> <span class="o">=</span> <span class="mi">3</span><span class="p">);</span>
  <span class="p">}</span>
<span class="p">}</span> 
  
<span class="n">backing</span><span class="p">(</span><span class="n">corner_points</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></figure>

<p>The hull function with a bunch of half-sphere creates the following flat-backed object that is free of sharp edges!</p>

<p><img src="/assets/openscad_backing.png" alt="A flat-backed, rounded edge square" /></p>

<h3 id="holder">Holder</h3>

<p>To make a C-shaped section, we can use a for-loop to rotate an object some
radius from the center. This allows us to define the opening in terms of
degrees. If we used a cube() form that went the full 360 degrees, then we
would have a cylinder with a cylindrical hole. Again, to avoid sharp edges,
the form that will be dragged around in space will be a capsule, which is a
cylinder with spheres at the end.</p>

<p>To create the C-shape, we rotate the object and then have it be translated out
by the radius as provided by the argument</p>

<figure class="highlight"><pre><code class="language-c" data-lang="c"><table class="rouge-table"><tbody><tr><td class="gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
</pre></td><td class="code"><pre><span class="n">module</span> <span class="nf">capsule</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">15</span><span class="p">,</span> <span class="n">h</span><span class="o">=</span><span class="mi">30</span><span class="p">)</span>
<span class="p">{</span>
  <span class="n">hull</span><span class="p">()</span>
  <span class="p">{</span>
    <span class="n">translate</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">h</span><span class="o">/</span><span class="mi">2</span><span class="p">])</span>
      <span class="n">sphere</span><span class="p">(</span><span class="n">r</span> <span class="o">=</span> <span class="n">radius</span><span class="p">,</span> <span class="err">$</span><span class="n">center</span> <span class="o">=</span> <span class="nb">true</span><span class="p">,</span> <span class="err">$</span><span class="n">fn</span><span class="o">=</span><span class="n">global_fn</span><span class="p">);</span>
    <span class="n">translate</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">-</span><span class="n">h</span><span class="o">/</span><span class="mi">2</span><span class="p">])</span>
      <span class="n">sphere</span><span class="p">(</span><span class="n">r</span> <span class="o">=</span> <span class="n">radius</span><span class="p">,</span> <span class="err">$</span><span class="n">center</span> <span class="o">=</span> <span class="nb">true</span><span class="p">,</span> <span class="err">$</span><span class="n">fn</span><span class="o">=</span><span class="n">global_fn</span><span class="p">);</span>
  <span class="p">}</span> 
<span class="p">}</span>

<span class="n">module</span> <span class="nf">clamp</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">5</span><span class="p">,</span> <span class="n">thickness</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">degrees</span><span class="o">=</span><span class="mi">220</span><span class="p">)</span>
<span class="p">{</span>
    <span class="n">max_i</span> <span class="o">=</span> <span class="n">round</span><span class="p">(</span><span class="n">degrees</span><span class="o">/</span><span class="mi">10</span><span class="p">);</span>

    <span class="k">for</span><span class="p">(</span><span class="n">i</span> <span class="o">=</span> <span class="p">[</span><span class="mi">0</span> <span class="o">:</span> <span class="mi">1</span> <span class="o">:</span> <span class="n">max_i</span><span class="p">])</span>
    <span class="p">{</span>
      <span class="n">rotate</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="n">i</span><span class="o">*</span><span class="mi">10</span><span class="p">])</span>
      <span class="n">translate</span><span class="p">([</span><span class="n">radius</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">])</span>
        <span class="n">capsule</span><span class="p">(</span><span class="n">thickness</span><span class="p">,</span> <span class="n">height</span><span class="p">);</span>
    <span class="p">}</span>
<span class="p">}</span>

<span class="n">translate</span><span class="p">([</span><span class="o">-</span><span class="mi">20</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">])</span> <span class="n">capsule</span><span class="p">();</span>
<span class="n">clamp</span><span class="p">();</span>
</pre></td></tr></tbody></table></code></pre></figure>

<p>The above snippet will let you make a pill-shaped object and then to turn that
into a C-shaped clamp.</p>

<p><img src="/assets/openscad_clamp.png" alt="Basic clamp" /></p>

<h3 id="bringing-it-together">Bringing it together</h3>

<p>We can now combine the backing and the clamp. However, we have a problem if we
just try to have the backing be the clamp radius away from the center of the
C-clamp. What we can do is consider the degrees argument that we send to the
clamp, divide it by two, and then do our operations:</p>

<figure class="highlight"><pre><code class="language-c" data-lang="c"><table class="rouge-table"><tbody><tr><td class="gutter gl"><pre class="lineno">1
2
3
4
5
6
7
8
9
10
11
12
13
</pre></td><td class="code"><pre><span class="n">module</span> <span class="nf">razor_holder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">thickness</span><span class="o">=</span><span class="mi">3</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">degrees</span><span class="p">,</span>
<span class="n">backing_points</span><span class="p">,</span> <span class="n">backing_h</span> <span class="o">=</span> <span class="mi">3</span><span class="p">)</span>
<span class="p">{</span> 

      <span class="n">clamp</span><span class="p">(</span><span class="n">radius</span> <span class="o">-</span> <span class="n">thickness</span><span class="p">,</span> <span class="n">thickness</span><span class="p">,</span> <span class="n">height</span><span class="p">,</span> <span class="n">degrees</span><span class="p">);</span>

      <span class="n">rotate</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="n">degrees</span><span class="o">/</span><span class="mi">2</span><span class="p">])</span>
        <span class="n">translate</span><span class="p">([</span><span class="n">radius</span><span class="o">+</span><span class="n">backing_h</span><span class="o">/</span><span class="mi">2</span><span class="p">,</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">])</span>
          <span class="n">rotate</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span><span class="o">-</span><span class="mi">90</span><span class="p">,</span><span class="mi">0</span><span class="p">])</span>
            <span class="n">backing</span><span class="p">(</span><span class="n">backing_points</span><span class="p">,</span> <span class="n">backing_h</span><span class="p">);</span>
<span class="p">}</span>

<span class="n">razor_holder</span><span class="p">(</span><span class="mi">10</span><span class="p">,</span> <span class="mi">3</span><span class="p">,</span> <span class="mi">10</span><span class="p">,</span> <span class="mi">220</span><span class="p">,</span> <span class="n">corner_points</span><span class="p">,</span> <span class="mi">3</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></figure>

<p>Here‚Äôs a happy rendering of a razor-holder able to hold one razor that‚Äôs 10mm in
diameter at the point where we want it to be held.</p>

<p><img src="/assets/openscad_razor_holder.png" alt="Finished Razor Holder" /></p>

<p>Before printing, a quick check can be done. Since the diameters of the various
razors and brushes were mesured, we can put in a cylinder after the
razor_holder() call and see what actually will fit in the holder.</p>

<p>I <em>highly</em> 
reccommend a little bit of checking with some of those previously measured
critical dimensions. The first argument to our function was originally not exactly the
inner radius, as the body of rotation has its own thickness, so the available
space is the radius minus the thickness of our holder. That‚Äôs why the clamp()
called in razor_holder() takes the radius argument and subtracts the thickness argument.</p>

<p>In more complicated
models the various operations can result in errors of various sorts that a
quick check such as this can expose. With parameterization you can tweak
yourself out of these error situations, but use judgement on refactoring a
model if the tweaking process is cumbersome or confusing. If you start to
internalize the dialing-in process with the test, then you might as well just
fold that into the model, yeah? But if it‚Äôs a single-purpose item or an artsy
piece that doesn‚Äôt require re-use and adjustment, then don‚Äôt break your back
trying to make the model beautifully and intuitively parameterized.</p>

<p>Also in more complicated models, where there are many critital dimensions,
having a more complete set of ‚Äúdummy‚Äù parts or as a whole separate module not
intended to be printed can
be added to the preview (but not rendered) to check if the requirements are
met or if more changes are needed. This can be helpful to also spot unusual
coupling where adjusting one thing causes ‚Äúsurprise‚Äù changes somewhere else.</p>

<figure class="highlight"><pre><code class="language-c" data-lang="c"><table class="rouge-table"><tbody><tr><td class="gutter gl"><pre class="lineno">1
2
3
</pre></td><td class="code"><pre><span class="cm">/* A simple test, for OpenSCAD objects */</span>
<span class="n">color</span><span class="p">([</span><span class="mi">0</span><span class="p">,</span><span class="mi">0</span><span class="p">.</span><span class="mi">9</span><span class="p">,</span><span class="mi">0</span><span class="p">.</span><span class="mi">2</span><span class="p">])</span>
<span class="n">cylinder</span><span class="p">(</span><span class="n">h</span><span class="o">=</span><span class="mi">100</span><span class="p">,</span><span class="n">d</span><span class="o">=</span><span class="mi">15</span><span class="p">,</span> <span class="n">center</span><span class="o">=</span><span class="nb">true</span><span class="p">);</span>
</pre></td></tr></tbody></table></code></pre></figure>

<p><img src="/assets/openscad_razor_holder_verified.png" alt="Finished Razor Holder" /></p>

<p>If the output doesn‚Äôt look right, but a few adjustments of the input
parameters get you there, but if the item in question is going to be re-used
a lot, then it might be worth revisiting the model so that
the inputs aren‚Äôt belying a surprise or two. For example, we could have the
radius argument be summed with the thickness (radius of the C-shaped clamp) so
the input for the clamp radius is truly the clamp radius.</p>

<p>Since I‚Äôm happy with this output knowing that it will match a razor, it‚Äôs time to render (hotkey F6) and then export the
rendering to an STL (hotkey F7). Rendering takes a while because of the 
way we‚Äôve created multiple hull objects and iterated over them in a for-loop.
You can adjust the step size per degree (as long as the maximum number of
iterations is also updated) to create a lower ‚Äúresolution‚Äù, or go the other
way and increase the number of iterations and lower the rotation associated
with each step to create a higher resolution volume of rotation.</p>

<p>In prusaslicer, we can use Place on Face (hotkey F) and select the backing as
‚Äúface-down‚Äù for printing.</p>

<p>Fire away with the desired material and a low-ish infill (and potentially enjoy
the little problems that come upkwith 3D printing anything in general). The
result matching the white-bodied razor is shown below:</p>

<p><img src="/assets/openscad_razor_holder_irl.png" alt="Finished Razor Holder IRL" /></p>

<p>I can now create holders for most of the razors and brushes, with the
exception of the other brush with a round shape (not pictured above). For that I can have a disk
(cylinder) ‚Äúminus‚Äù a sphere where the radius is equal to the radius of the
brush body. It would a bit like a simple spoon shape, and then combine that to the backing with perhaps a rectangular arrangement of points since it‚Äôs 6cm across.</p>

<h2 id="conclusion">Conclusion</h2>

<p>The process for creating a practical object can be a bit iterative and
frustrating, but each step can be figured out
incrementally to produce the final model. By first prototyping with
sketches, you can work out some important dimensions or constraints to work
with. If you can do stuff in physical space you can arrange objects, trace
outlines, and make measurements of things as you have arranged them.</p>

<p>After getting a sense of what the final end piece is, break down the model
into smaller modules and work out each of them in turn. Once the elements are
built up, bring these elements together.</p>

<p>If the small parts are more or less where they need to be, then the
integration step can be smoother than trying to design and integrate many
different parts all at the same time.</p>

<p>Once the model has been made, a few
final checks can easily be done with ‚Äúdummy‚Äù models representing critial
dimensions. This might be one object like the cylinder-check for this object,
or it can be a whole virtual jig.</p>

<p>If the final checks and tweaks look good, then it‚Äôs on to printing the
object(s).
Happy designing and printing!</p>
:ET